# Generated by Django 5.2.6 on 2025-09-14 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='coffeeis/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('BL', 'BLACK'), ('WH', 'WHITE'), ('ES', 'ESPRESSO'), ('CA', 'CAPPUCCINO'), ('LT', 'LATTE'), ('FR', 'FRAPPUCCINO'), ('IC', 'ICED COFFEE'), ('OT', 'OTHER')], max_length=2)),
            ],
        ),
    ]
