# Generated by Django 5.2.6 on 2025-09-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeevariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
