# Generated by Django 5.2.6 on 2025-09-15 02:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffeevariety_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_number', models.CharField(max_length=100)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('coffee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='coffee.coffeevariety')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coffee.coffeevariety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('coffee_varieties', models.ManyToManyField(related_name='stores', to='coffee.coffeevariety')),
            ],
        ),
    ]
